#!/bin/bash
NAME=PSCnomics
DIR=/home/pscnomics/pscnomics-web
USER=pscnomics
GROUP=pscnomics
WORKERS=2
THREADS=2
CONNS=100
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/.venv/bin/activate
# unix:$DIR/run/gunicorn.sock
BIND=127.0.0.1:8089
LOG_LEVEL=info

cd $DIR
source $VENV
exec gunicorn main:app \
  --name $NAME \
  --workers $WORKERS \
  --threads $THREADS \
  --worker-class $WORKER_CLASS \
  --worker-connections=$CONNS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-